apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: PayrollConfigurationApi
  description: Set of APIs for accessing & configuring static payroll data -
    Earnings, Deductions, Tax Codes, Code Groups, Pay Groups, Job Codes.
  labels:
    access: internal
  tags:
    - earnings
    - deductions
    - taxcodes
    - codegroups
    - paygroups
    - payrollconfiguration
    - payroll
    - payrollapis
  links:
    - url: https://app.datadoghq.com/apm/services/payrollconfigurationapi
      title: APM
      icon: dashboard
    - url: https://tink8sapp.qa.paylocity.com/PayrollConfigurationApi/swagger
      title: Swagger For Tin Environment
      icon: techdocs
    - url: https://github.com/Paylocity/payr-paylocity.apis.payroll.configuration
      title: Repository
      icon: github
    - url: https://rancher.paylocity.com/dashboard/c/c-lnd9s/explorer/apps.deployment/pcty-payroll/payrollconfigurationapi
      title: Rancher
      icon: dashboard
relations:
  - type: apiConsumedBy
    target:
      kind: component
      name: wayback-search
  - type: apiProvidedBy
    target:
      kind: component
      name: wayback-archive    
spec:
  type: business domain
  lifecycle: development
  owner: PayrollApiEngineering
  definition: 
    $text: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml
